const express = require("express")
const { userRegistration, verifyUser, userProtected } = require("../controller/userLogin")
const authenticationToken = require("../middlwares/authMiddleware")
const get_doctor_data = require("../controller/getDoctorData")
const { addPatientAppointmentData, getPatientAppointmentData, deleteAppointmentData } = require("../controller/patientAppointmentdata")
const { updateBillUsernameUser } = require("../controller/billingData")
const { addFeedback, addQuery, getFeedbackData } = require("../controller/queryFeedback")
const router = express.Router()
router.post("/registration_data", userRegistration)
router.post("/signin_data", verifyUser)
router.get("/protected", authenticationToken, userProtected)
router.get('/get_doctor_data', get_doctor_data)
router.post('/add_patient_appointment', addPatientAppointmentData)
router.get('/get_patient_appointment_data', getPatientAppointmentData)
router.delete('/delete_appointment_data/:id', deleteAppointmentData)
router.put('/add_bill_to_username/:billId', updateBillUsernameUser)
router.post('/add_feedback', addFeedback)
router.post('/add_query', addQuery)
router.get('/get_feedback_data', getFeedbackData)
const userRouter = router
module.exports = userRouter